export const GET_ITEMS = 'GET_ITEMS'
export const FIND_ITEMS = 'FIND_ITEMS'


export const CATEGORY_UP = 'CATEGORY_UP'
export const CATEGORY_DOWN = 'CATEGORY_DOWN'
export const DEL_CATEGORY = 'DEL_CATEGORY'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORYNAME = 'UPDATE_CATEGORYNAME'
export const SUBCATEGORY_DOWN = 'SUBCATEGORY_DOWN'
export const SUBCATEGORY_UP = 'SUBCATEGORY_UP'

export const DEL_SUBCATEGORY = 'DEL_SUBCATEGORY'
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY'


